services:
  server:
    build:
      context: .
      target: final
    environment:
      - SEVERVER=${SERVER:-0.0.0.0}
      - PORT=${PORT:-8080}
      - SERVER_LOKI=${SERVER_LOKI:-127.0.0.1} # IP HOST THAT DOCKER IS RUNNING.
      - PORT_LOKI=${PORT_LOKI:-3100}
      - JOB=${JOB:-example-app}
    ports:
      - ${PORT:-8080}:${PORT:-8080}
